version: '2'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  redis:
    image: redis
    ports:
      - '6379:6379'
  mongo1:
    image: mongo
    ports:
      - '27018:27017'
  redis1:
    image: redis
    ports:
      - '6380:6379'
